name: Hyperexecute-Cucumber
on:
  # workflow_dispatch:
    #inputs:
      # username:
      #   required: true
      #   description: LT Username
      # accessKey:
      #   description: LT Access Key
      #   required: true
      # sampleRepoLink:
       push:
    #only trigger on branches, not on tags
        branches: '**'
        # description: Link to the HyperExecute sample repo
        # default: https://github.com/prateekLambda/cucumber-selenium-hyperexecute-sample.git
        # required: false
jobs:
   #Cucumber-Sample-Hyperexeucte:
    clone:
      runs-on: ${{ matrix.os }}
      timeout-minutes: 15
      strategy:
       fail-fast: false
       matrix:
         os: [windows-latest]
      
      steps:
       - name: Checkout sources
         uses: actions/checkout@v2
         with:
          owner: prateekLambda
          repository: https://github.com/prateekLambda/cucumber-selenium-hyperexecute-sample.git
            
       - name: Starting CLI testing
         shell: bash
         run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ secrets.LT_USERNAME }}
              export LT_ACCESS_KEY=${{ secrets.LT_ACCESSKEY }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --download-artifacts --force-clean-artifacts --labels $jobLabel
              # cd .hyperexecute
              # ls -la
              # jq .summary.job_link result.json>out.tmp
              # echo "HyperExecute Job Dashboard Link:"
              # cat out.tmp
              echo "Test completion"
