name: Hyperexecute-Cucumber
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true
      sampleRepoLink:
        description: Link to the HyperExecute sample repo
        default: https://github.com/prateekLambda/cucumber-selenium-hyperexecute-sample.git
        required: true
jobs:
  Cucumber-Sample-Hyperexeucte:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-queued:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-elevn:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-three:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-four:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-five:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-seven:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-eight:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-nine:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
              
  Cucumber-Sample-Hyperexeucte-ten:
    runs-on: ${{ matrix.os }}
    concurrency:
     group: ci-${{ github.ref }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              cd cucumber-selenium-hyperexecute-sample
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              echo $LT_USERNAME
              echo $LT_ACCESS_KEY
              echo "Setting Job label as Jira ticket number"
              export jobLabel="HYP-568"
              echo $jobLabel
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track --download-artifacts --force-clean-artifacts --labels $jobLabel
              cd .hyperexecute
              jq .summary.job_link result.json>out.tmp
              echo "HyperExecute Job Dashboard Link:"
              cat out.tmp
              echo "Test completion"
   
